# RAW DATASET TO USE
data: extra/dataset.csv

# RAW DATA PROCESSING
processing:
    resample: true
    time: D
    aggregate: {
        Open: first,
        High: max,
        Low: min,
        Close: last,
        Volume: sum
    }
    label:
        from: Close
        shift: 1

# FEATURE EXTRATION
features:
    add: [SK, SD, Momentum]
    window: 14
    filter: [Close, Momentum, SD, Label]

# MODEL ENSAMBLE
ensamble:
    models:
        - linreg:
            split:
                train: 0.8
                test: 0.2
        - lstm:
            split:
                train: 0.6
                test: 0.2
                validation: 0.2
            layers:
                - lstm:
                    value: 120
                    activation: relu
                - dropout:
                    value: 0.15
                - dense:
                    value: 50
                    activation: relu
                - dense:
                    value: 1
            epochs: 20
            batch: 8
            validation: 25
            loss: mean_squared_error
            optimizer: rmsprop
    decision: mean

# MODEL TRAINING PARAMS
training:
    linreg:
    lstm:
        layers:
            - lstm:
                nodes: 120
                activation: relu
            - dropout:
                nodes: 0.15
            - dense:
                nodes: 50
                activation: relu
            - dense:
                nodes: 1
        epochs: 20
        batch: 8
        validation: 25