#data:
#    source: some API
#    from: date
#    to: date
#    formatting: min | hour | day

# TEMP DATASET TO USE
data: extra/dataset.csv

# RAW DATA PROCESSING
processing:
    resample: true
    time: D
    aggregate: {
        Open: first,
        High: max,
        Low: min,
        Close: last,
        Volume: sum
    }
    label:
        from: Close
        shift: 1

# FEATURE INJECTION
features:
    category: all
    window: 14

# TRAIN/TEST SPLITTING
splitting:
    train_split: 0.8
    validation_folds: 5

# MODEL ENSEMBLE
regression_ensemble:
    models:
        - linreg:
        - lstm:
            morph:
                window: 4
                batch: 30
            layers:
                - lstm:
                    value: 120
                - dropout:
                    value: 0.15
                - dense:
                    value: 50
                    activation: relu
                - dense:
                    value: 1
            epochs: 15
            loss: mean_squared_error
            optimizer: rmsprop

classification_ensemble:
    decision:
        name: quantile
        upper: 0.75
        lower: 0.25
        #name: threshold
        #value: 0.003
    models:
        - logreg:
        - rand_forest: