#data:
#    source: some API
#    from: date
#    to: date
#    formatting: min | hour | day

# TEMP DATASET TO USE
data: extra/dataset.csv

# RAW DATA PROCESSING
processing:
    resample: true
    time: D
    aggregate: {
        Open: first,
        High: max,
        Low: min,
        Close: last,
        Volume: sum
    }
    label:
        from: close
        shift: 1

# FEATURE EXTRATION
features:
    add: [sk, sd, momentum]
    window: 14
    filter: [close, momentum, sd, label]

# TRAIN/TEST SPLITTING
splitting:
    train_split: 0.8
    validation_folds: 5

# MODEL ENSEMBLE
ensemble:
    models:
        - linreg:
        - linreg:
        - linreg:
        - linreg:
        - linreg:
        - lstm:
            layers:
                - lstm:
                    value: 120
                    activation: relu
                - dropout:
                    value: 0.15
                - dense:
                    value: 50
                    activation: relu
                - dense:
                    value: 1
            epochs: 5
            batch: 8
            loss: mean_squared_error
            optimizer: rmsprop