data: extra/dataset.csv
ensemble:
  decision: mean
  models:
  - linreg:
      split:
        test: 0.2
        train: 0.8
  - lstm:
      batch: 8
      epochs: 20
      layers:
      - lstm:
          activation: relu
          value: 120
      - dropout:
          value: 0.15
      - dense:
          activation: relu
          value: 50
      - dense:
          value: 1
      loss: mean_squared_error
      optimizer: rmsprop
      split:
        test: 0.2
        train: 0.6
        validation: 0.2
      validation: 25
features:
  add:
  - SK
  - SD
  - Momentum
  filter:
  - Close
  - Momentum
  - SD
  - Label
  window: 14
processing:
  aggregate:
    Close: last
    High: max
    Low: min
    Open: first
    Volume: sum
  label:
    from: Close
    shift: 1
  resample: true
  time: D
