data: extra/dataset.csv
features:
  add:
  - SK
  - SD
  - Momentum
  filter:
  - Close
  - Momentum
  - SD
  - Label
  window: 14
model: lstm
processing:
  aggregate:
    Close: last
    High: max
    Low: min
    Open: first
    Volume: sum
  label:
    from: Close
    shift: 1
  resample: true
  time: D
training:
  batch: 8
  epochs: 20
  validation: 25
